[package]
name = "apalis-redis"
version = "0.3.4"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
readme = "../../README.md"

license = "MIT"
description = "Redis Storage for Apalis: simple and reliable background processing based on Actix Actors"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apalis-core = { path = "../../packages/apalis-core", version = "0.3.4", default-features = false }
redis = { version = "0.21" , features = ["tokio-comp"] }
serde = "1"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
serde_json = "1"
async-stream = "0.3"
futures = "0.3"
tokio = "1"
async-trait = "0.1.53"

[features]
default = ["storage"]
storage = ["apalis-core/storage"]
pubsub = ["apalis-core/worker"]